language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  github_token: $github_token
  domain: ense701s12020group3.surge.sh
  project: ./build/
on:
  branch: master
branches:
  only:
  - master