language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: ENSE701S12020Group3.surge.sh
  project: ./build/
on:
  branch: master